#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""output.py — digest writer + proposal enqueue for the self_review package.

No LLM calls, no network, stdlib only.
"""
from __future__ import annotations

import datetime as dt
import json
import re
from pathlib import Path
from typing import Any

# scripts/ directory — one level above this package
_SCRIPTS_DIR = Path(__file__).resolve().parent.parent

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug(text: str, maxlen: int = 40) -> str:
    """Turn free text into a URL/filename-safe slug."""
    s = _SLUG_RE.sub("-", text.lower()).strip("-")
    return s[:maxlen].strip("-")


# ---------------------------------------------------------------------------
# Digest rendering helpers
# ---------------------------------------------------------------------------

def _render_mining_section(mined: dict[str, Any]) -> list[str]:
    """Return lines for the ## Mining Findings section."""
    lines: list[str] = ["## Mining Findings", ""]
    corrections = mined.get("corrections") or []
    rituals = mined.get("rituals") or []
    sequences = mined.get("sequences") or []
    if not (corrections or rituals or sequences):
        lines.append("_No mining findings in window._")
        return lines
    for c in corrections:
        quote = (c.get("representative_quote") or "")[:200]
        lines.append(
            f"- **User correction cluster** (×{c.get('count', '?')}): {quote!r}"
        )
    for r in rituals:
        lines.append(
            f"- **Bash ritual** (×{r.get('count', '?')}): `{r.get('command_shape', '?')}`"
        )
    for s in sequences:
        seq = " → ".join(s.get("sequence") or [])
        lines.append(
            f"- **Tool sequence** ({s.get('session_count', '?')} sessions): `{seq}`"
        )
    return lines


def _render_efficiency_section(efficiency_findings: list[dict[str, Any]]) -> list[str]:
    """Return lines for the ## Efficiency Findings section."""
    lines: list[str] = ["## Efficiency Findings", ""]
    if not efficiency_findings:
        lines.append("_No efficiency signals detected._")
        return lines
    for f in efficiency_findings:
        sev = f.get("severity", "?")
        signal = f.get("signal", "")
        evidence = f.get("evidence", "")
        lines.append(f"- [{sev}] {signal} — `{evidence}`")
    return lines


def _render_apply_plan_section(queued_paths: list[str]) -> list[str]:
    """Return lines for the ## Apply plan section (deep mode only)."""
    lines: list[str] = [
        "## Apply plan",
        "",
        "Items marked SAFE may be auto-applied by the host LLM. "
        "Items marked RISKY or DECISION require user confirmation.",
        "",
        "| Path | classify_hint |",
        "|---|---|",
    ]
    for qp in queued_paths:
        p = Path(qp)
        hint = "?"
        try:
            content = p.read_text()
            for line in content.splitlines()[:10]:
                if line.startswith("classify_hint:"):
                    hint = line.split(":", 1)[1].strip()
                    break
        except OSError:
            pass
        lines.append(f"| `{qp}` | {hint} |")
    return lines


def render_digest(
    *,
    mode: str,
    window_days: int,
    mined: dict[str, Any],
    efficiency_findings: list[dict[str, Any]],
    queued_paths: list[str],
    generated_at: dt.datetime,
    is_deep: bool,
) -> str:
    """Return the markdown digest string."""
    total = len(efficiency_findings) + len(mined.get("corrections") or [])
    if efficiency_findings:
        top_theme = efficiency_findings[0].get("kind", "").replace("_", " ")
    elif mined.get("corrections"):
        top_theme = "recurring user corrections"
    else:
        top_theme = "no significant signals"

    lines: list[str] = [
        f"# Self-Review Digest — {generated_at.date().isoformat()} ({mode})",
        "",
        f"**{total} finding(s)** | window: {window_days}d | top theme: {top_theme}",
        f"Generated: {generated_at.isoformat(timespec='seconds')} UTC",
        "",
    ]
    lines.extend(_render_mining_section(mined))
    lines.append("")
    lines.extend(_render_efficiency_section(efficiency_findings))
    lines.append("")

    lines.append("## Queued Proposals")
    lines.append("")
    if not queued_paths:
        lines.append("_No proposals enqueued._")
    else:
        for qp in queued_paths:
            lines.append(f"- `{qp}`")
    lines.append("")

    if is_deep and queued_paths:
        lines.extend(_render_apply_plan_section(queued_paths))
        lines.append("")

    lines.append("---")
    lines.append("Generated by `self_review`. No LLM. No network. Local stdlib only.")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Classify hint helpers
# ---------------------------------------------------------------------------

def _classify_hint(finding: dict[str, Any]) -> str:
    """Heuristic classify_hint: SAFE for doc/test/lint; RISKY for runtime/multi-file."""
    kind = finding.get("kind", "")
    action = finding.get("suggested_action", "").lower()
    risky_signals = (
        "schema", "migration", "runtime", "multi-file", "split", "stabilising",
        "auth", "security", "production",
    )
    if any(s in action for s in risky_signals):
        return "RISKY"
    if kind == "high_churn_file":
        return "RISKY"
    if kind in ("phase_repeated_failure", "criterion_recurring_failure"):
        return "SAFE"
    return "SAFE"


def _try_classify_action(workdir: Path, finding: dict[str, Any]) -> str:
    """Attempt to use classify_action.py's importable `classify()`. Fall back to heuristic."""
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "classify_action", _SCRIPTS_DIR / "classify_action.py"
        )
        if spec is None or spec.loader is None:
            return _classify_hint(finding)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
        mod.classify(workdir, command="", files_touched=[], envelope={})
    except Exception:  # noqa: BLE001
        pass
    return _classify_hint(finding)


# ---------------------------------------------------------------------------
# Frontmatter + body builders
# ---------------------------------------------------------------------------

def _make_frontmatter(
    *,
    source: str = "self-review",
    mode: str,
    severity: str,
    classify_hint: str,
    created_ts: str,
    target: str | None = None,
) -> str:
    lines = [
        "---",
        f"source: {source}",
        f"mode: {mode}",
        f"severity: {severity}",
        f"classify_hint: {classify_hint}",
        f"created_ts: {created_ts}",
    ]
    if target is not None:
        lines.append(f"target: {target}")
    lines += ["---", ""]
    return "\n".join(lines)


def _build_proposal_body(
    item: dict[str, Any],
    hint: str,
    is_self: bool,
) -> str:
    """Build the markdown body for a single proposal file."""
    kind = item.get("kind", "finding")
    severity = item.get("severity", "LOW")
    body_lines = [
        f"## Finding: {item.get('signal', '')}",
        "",
        f"**Kind**: `{kind}`",
        f"**Severity**: {severity}",
        f"**Classify hint**: {hint}",
        "",
        "### Evidence",
        "",
        "```",
        item.get("evidence", ""),
        "```",
        "",
        "### Suggested fix",
        "",
        item.get("suggested_action", ""),
        "",
    ]
    if is_self:
        body_lines += [
            "### Self-modification gate",
            "",
            "This proposal modifies build-loop's own code. Before committing, run:",
            "```",
            "python3 scripts/self_mod_verify.py --workdir . --scope full "
            "--auto-revert --json",
            "```",
            "Commit ONLY if verdict == \"pass\".",
            "",
        ]
    mined_data = item.get("_mined_data")
    if mined_data:
        body_lines += [
            "### Mined data",
            "",
            "```json",
            json.dumps(
                {k: v for k, v in mined_data.items() if k not in ("_mined_data", "_target")},
                indent=2,
            ),
            "```",
            "",
        ]
    return "\n".join(body_lines)


def _write_single_proposal(
    *,
    path: Path,
    item: dict[str, Any],
    mode: str,
    workdir: Path,
    created_ts: str,
) -> None:
    """Write one proposal .md file."""
    severity = item.get("severity", "LOW")
    is_self = item.get("_target") == "self"
    hint = "SAFE" if is_self else _try_classify_action(workdir, item)
    frontmatter = _make_frontmatter(
        mode=mode,
        severity=severity,
        classify_hint=hint,
        created_ts=created_ts,
        target="self" if is_self else None,
    )
    body = _build_proposal_body(item, hint, is_self)
    path.write_text(frontmatter + body)


def _build_items_list(
    efficiency_findings: list[dict[str, Any]],
    self_simplification: list[dict[str, Any]],
    mined: dict[str, Any],
) -> list[dict[str, Any]]:
    """Combine all finding sources into one ordered items list."""
    items: list[dict[str, Any]] = list(efficiency_findings)
    for c in mined.get("corrections") or []:
        items.append({
            "kind": "user_correction_cluster",
            "signal": f"Recurring user correction (×{c.get('count', '?')})",
            "evidence": (c.get("representative_quote") or "")[:200],
            "suggested_action": (
                "Encode this correction pattern as a feedback_*.md note in CLAUDE.md "
                "or add a check/skill to prevent the need for future corrections."
            ),
            "severity": "MEDIUM",
            "_mined_data": c,
        })
    for r in mined.get("rituals") or []:
        items.append({
            "kind": "bash_ritual_candidate",
            "signal": f"Repeated bash ritual (×{r.get('count', '?')}): `{r.get('command_shape', '')}`",
            "evidence": r.get("command_shape", ""),
            "suggested_action": (
                "Consider wrapping this repeated shell shape in a script or adding it to /schedule."
            ),
            "severity": "LOW",
            "_mined_data": r,
        })
    for s in self_simplification:
        items.append({**s, "_target": "self"})
    return items


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_proposals(
    *,
    proposals_dir: Path,
    date_str: str,
    mode: str,
    efficiency_findings: list[dict[str, Any]],
    self_simplification: list[dict[str, Any]],
    mined: dict[str, Any],
    workdir: Path,
    created_ts: str,
    cap: int | None,
) -> list[str]:
    """Write one .md proposal file per actionable finding. Returns list of paths written."""
    proposals_dir.mkdir(parents=True, exist_ok=True)
    items = _build_items_list(efficiency_findings, self_simplification, mined)
    if cap is not None:
        items = items[:cap]

    paths: list[str] = []
    for idx, item in enumerate(items):
        kind = item.get("kind", "finding")
        signal_text = item.get("signal", "")
        slug = _slug(f"{kind}-{signal_text}", 40)
        filename = f"self-review-{date_str}-{idx:02d}-{slug}.md"
        path = proposals_dir / filename
        _write_single_proposal(
            path=path,
            item=item,
            mode=mode,
            workdir=workdir,
            created_ts=created_ts,
        )
        paths.append(str(path))
    return paths
