#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross
# SPDX-License-Identifier: Apache-2.0
"""Idempotent installer for the Rally Point git hooks.

Installs (or chains) two hooks in a consumer repo:

  - ``.git/hooks/post-commit`` — emits a ``commit`` (and, for manifest
    changes, a ``dep-change``) record + bumps the channel revision so a
    commit by ANY tool is captured cross-tool.
  - ``.git/hooks/pre-commit`` — the private-slug guard. Blocks a commit
    that stages a private app slug (denylist in
    ``scripts/check_private_slugs.py``). Only meaningful inside the
    build-loop plugin repo itself, but the installer is harmless
    elsewhere — it stages a copy of ``check_private_slugs.py`` whose
    denylist a consumer can edit or empty.

Contract:
  - only operates inside a git repo (``.git`` present);
  - idempotent: re-running makes no further change (marker-guarded);
  - never clobbers a pre-existing post-commit — the Rally Point segment is
    appended/chained, unrelated content is preserved verbatim;
  - the hook body is fire-and-forget (it backgrounds the capture and
    ``exit 0`` so a commit can never be slowed or failed).

The capture logic is written next to the hook as a self-contained
``.git/hooks/.rally-point-capture.py`` that pins the absolute path of
*this* plugin's ``scripts/rally_point`` package (recorded at install
time), so the hook keeps working regardless of the committing tool's
cwd or sys.path.
"""
from __future__ import annotations

import os
import re
import stat
import subprocess
from pathlib import Path

MARKER = "# --- BEGIN rally-point post-commit ---"
MARKER_END = "# --- END rally-point post-commit ---"
LEGACY_MARKER = "# --- BEGIN app-pulse post-commit ---"
LEGACY_MARKER_END = "# --- END app-pulse post-commit ---"
LEGACY_SEGMENT_RE = re.compile(
    rf"{re.escape(LEGACY_MARKER)}.*?{re.escape(LEGACY_MARKER_END)}\n?",
    re.DOTALL,
)

_PKG_DIR = Path(__file__).resolve().parent
_HOOK_TEMPLATE = (_PKG_DIR.parent.parent / "hooks" / "post-commit")

SEGMENT_RE = re.compile(
    rf"{re.escape(MARKER)}.*?{re.escape(MARKER_END)}\n?",
    re.DOTALL,
)

_SEGMENT = f'''{MARKER}
RALLY_POINT_TOPLEVEL="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$RALLY_POINT_TOPLEVEL" ]; then
  echo "rally-point post-commit: cannot resolve repo toplevel" >&2
  exit 2
fi
RALLY_POINT_CAPTURE="$RALLY_POINT_TOPLEVEL/.git/hooks/.rally-point-capture.py"
if [ -f "$RALLY_POINT_CAPTURE" ]; then
  ( python3 "$RALLY_POINT_CAPTURE" >/dev/null 2>&1 ) </dev/null >/dev/null 2>&1 &
fi
{MARKER_END}
'''

# --- private-slug-guard pre-commit ---
PRE_MARKER = "# --- BEGIN private-slug-guard pre-commit ---"
PRE_MARKER_END = "# --- END private-slug-guard pre-commit ---"

# The pinned guard script next to the hook resolves the plugin's
# check_private_slugs.py recorded at install time, so the hook works
# regardless of the committing tool's cwd or sys.path.
PRE_SEGMENT_RE = re.compile(
    rf"{re.escape(PRE_MARKER)}.*?{re.escape(PRE_MARKER_END)}\n?",
    re.DOTALL,
)

_PRE_SEGMENT = f'''{PRE_MARKER}
RALLY_POINT_TOPLEVEL="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$RALLY_POINT_TOPLEVEL" ]; then
  echo "private-slug-guard: cannot resolve repo toplevel — refusing to skip the guard" >&2
  exit 2
fi
PRIVATE_SLUG_GUARD="$RALLY_POINT_TOPLEVEL/.git/hooks/.private-slug-check.py"
if [ -f "$PRIVATE_SLUG_GUARD" ]; then
  python3 "$PRIVATE_SLUG_GUARD" || exit 1
fi
{PRE_MARKER_END}
'''

_PRE_GUARD_SRC = '''#!/usr/bin/env python3
"""Auto-generated by rally_point.install_git_hook — do not edit.

Run by .git/hooks/pre-commit. Delegates to the plugin's pinned
check_private_slugs.py; a non-zero exit aborts the commit.
"""
import runpy
import sys

_CHECKER = {checker!r}
sys.argv = [_CHECKER]
try:
    runpy.run_path(_CHECKER, run_name="__main__")
except SystemExit as exc:
    sys.exit(exc.code or 0)
'''

_CAPTURE_SRC = '''#!/usr/bin/env python3
"""Auto-generated by rally_point.install_git_hook — do not edit.

Backgrounded by .git/hooks/post-commit. Fire-and-forget: any failure is
swallowed so a commit is never affected.
"""
import os
import subprocess
import sys

_PKG = {pkg!r}
if _PKG not in sys.path:
    sys.path.insert(0, _PKG)

MANIFEST_GLOBS = (
    "package.json", "package-lock.json", "pnpm-lock.yaml",
    "requirements.txt", "pyproject.toml", "uv.lock", "Cargo.toml",
    "go.mod", "Gemfile",
)


def _main():
    try:
        import channel_paths as ap
        import changes as ch
        import revision as rev
    except Exception:
        return
    try:
        repo = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        slug = ap.app_slug(cwd=repo)
        chan = ap.ensure_channel_dir(slug)
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        # --root makes the very first (parentless) commit list its
        # files too, otherwise diff-tree emits nothing for a root commit
        # and a first-commit manifest would never yield a dep-change.
        names = subprocess.run(
            ["git", "diff-tree", "--no-commit-id", "--name-only",
             "--root", "-r", "HEAD"],
            cwd=repo, capture_output=True, text=True, check=True,
        ).stdout.split()
        tool = (
            os.environ.get("RALLY_POINT_TOOL")
            or os.environ.get("APP_PULSE_TOOL")
            or "unknown"
        )
        model = (
            os.environ.get("RALLY_POINT_MODEL")
            or os.environ.get("APP_PULSE_MODEL")
            or "unknown"
        )
        run_id = (
            os.environ.get("RALLY_POINT_RUN_ID")
            or os.environ.get("APP_PULSE_RUN_ID")
            or "unknown"
        )
        ch.append_change(chan, ch.make_record(
            kind="commit", tool=tool, model=model, run_id=run_id,
            app_slug=slug, payload={{"sha": sha, "files": names}},
            revision=rev.read_revision(chan) + 1,
        ))
        manifest_hits = sorted(
            n for n in names if os.path.basename(n) in MANIFEST_GLOBS
        )
        if manifest_hits:
            ch.append_change(chan, ch.make_record(
                kind="dep-change", tool=tool, model=model, run_id=run_id,
                app_slug=slug,
                payload={{"sha": sha, "manifests": manifest_hits}},
                revision=rev.read_revision(chan) + 1,
            ))
        rev.bump_revision(chan)
    except Exception:
        return


if __name__ == "__main__":
    _main()
'''


def _is_git_repo(repo: Path) -> bool:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=str(repo), capture_output=True, text=True, check=True,
        ).stdout.strip()
        return bool(out)
    except (subprocess.CalledProcessError, OSError):
        return False


def _git_dir(repo: Path) -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=str(repo), capture_output=True, text=True, check=True,
    ).stdout.strip()
    p = Path(out)
    return p if p.is_absolute() else (Path(repo) / p)


def _make_executable(path: Path) -> None:
    st = os.stat(path)
    path.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _install_post_commit(hooks_dir: Path) -> None:
    """Install/chain the post-commit capture. Idempotent."""
    # The pinned capture script (rewritten each install — cheap, keeps
    # the package path current if the plugin moved).
    capture = hooks_dir / ".rally-point-capture.py"
    capture.write_text(_CAPTURE_SRC.format(pkg=str(_PKG_DIR)))
    capture.chmod(0o755)

    hook = hooks_dir / "post-commit"
    if not hook.exists():
        hook.write_text("#!/bin/sh\n" + _SEGMENT + "exit 0\n")
    else:
        body = hook.read_text()
        if MARKER in body:
            # Re-install: replace our segment in place so the pinned
            # capture wiring stays current if the plugin moved or the
            # segment template changed.
            hook.write_text(SEGMENT_RE.sub(_SEGMENT, body))
            _make_executable(hook)
            return
        if LEGACY_MARKER in body:
            hook.write_text(LEGACY_SEGMENT_RE.sub(_SEGMENT, body))
            _make_executable(hook)
            return
        # Preserve the existing hook verbatim; append our segment.
        if not body.endswith("\n"):
            body += "\n"
        hook.write_text(body + "\n" + _SEGMENT)
    _make_executable(hook)


def _install_pre_commit(hooks_dir: Path) -> None:
    """Install/chain the private-slug-guard pre-commit. Idempotent.

    The guard MUST be able to abort a commit, so (unlike post-commit)
    its segment exits non-zero on a hit. When chaining onto an existing
    pre-commit, the guard segment is appended last so a prior hook's
    own checks still run first.

    On re-install when our segment is already present, the segment is
    REPLACED in place (not early-returned). The segment text carries the
    pinned guard wiring; a re-install after the plugin moved, or after
    the segment template changed, must refresh it — early-returning
    would leave a stale segment that can silently disable the guard.
    """
    checker = _PKG_DIR.parent / "check_private_slugs.py"
    if not checker.exists():
        return  # nothing to guard with — skip silently
    guard = hooks_dir / ".private-slug-check.py"
    guard.write_text(_PRE_GUARD_SRC.format(checker=str(checker)))
    guard.chmod(0o755)

    hook = hooks_dir / "pre-commit"
    if not hook.exists():
        hook.write_text("#!/bin/sh\n" + _PRE_SEGMENT + "exit 0\n")
    else:
        body = hook.read_text()
        if PRE_MARKER in body:
            # Re-install: replace our (possibly stale) segment in place
            # so the pinned guard wiring is always current.
            hook.write_text(PRE_SEGMENT_RE.sub(_PRE_SEGMENT, body))
            _make_executable(hook)
            return
        if not body.endswith("\n"):
            body += "\n"
        hook.write_text(body + "\n" + _PRE_SEGMENT)
    _make_executable(hook)


def install(repo: Path) -> bool:
    """Install/chain both git hooks in ``repo``. Idempotent.

    Returns True on success, False if ``repo`` is not a git repo.
    """
    repo = Path(repo)
    if not _is_git_repo(repo):
        return False
    hooks_dir = _git_dir(repo) / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    _install_post_commit(hooks_dir)
    _install_pre_commit(hooks_dir)
    return True
