#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""Idempotent installer for the Rally Point git hooks.

Installs (or chains) two hooks in a consumer repo:

  - ``.git/hooks/post-commit`` — emits a ``commit`` (and, for manifest
    changes, a ``dep-change``) record + bumps the channel revision so a
    commit by ANY tool is captured cross-tool.
  - ``.git/hooks/pre-commit`` — public-repo hygiene guards. Blocks a
    commit that stages a private app slug (denylist in
    ``scripts/check_private_slugs.py``) or runtime memory/state files.
    The private-slug guard is installed ONLY where it can function: a
    repo carrying a ``.private-slugs`` denylist (or the tracked
    ``.private-slugs.example`` that documents one). It was previously
    installed everywhere on the belief that it was "harmless elsewhere".
    It is not: ``check_private_slugs.py`` exits 2 when the denylist is
    absent, and an empty denylist is rejected too ("add at least one slug
    or remove the guard"), so a repo with no denylist has NO passive
    configuration — every commit by every agent is blocked. Observed
    2026-08-20 in a private consumer repo, where the installer also
    re-created the guard after it was disabled by hand.

Contract:
  - only operates inside a git repo (``.git`` present);
  - idempotent: re-running makes no further change (marker-guarded);
  - never clobbers a pre-existing post-commit — the Rally Point segment is
    appended/chained, unrelated content is preserved verbatim;
  - the hook body is fire-and-forget (it backgrounds the capture and
    ``exit 0`` so a commit can never be slowed or failed).

The capture logic is written next to the hook as a self-contained
``.git/hooks/.rally-point-capture.py`` that pins the absolute path of
*this* plugin's ``scripts/rally_point`` package (recorded at install
time), so the hook keeps working regardless of the committing tool's
cwd or sys.path.
"""
from __future__ import annotations

import argparse
import os
import re
import stat
import subprocess
from pathlib import Path

MARKER = "# --- BEGIN rally-point post-commit ---"
MARKER_END = "# --- END rally-point post-commit ---"
LEGACY_MARKER = "# --- BEGIN app-pulse post-commit ---"
LEGACY_MARKER_END = "# --- END app-pulse post-commit ---"
LEGACY_SEGMENT_RE = re.compile(
    rf"{re.escape(LEGACY_MARKER)}.*?{re.escape(LEGACY_MARKER_END)}\n?",
    re.DOTALL,
)

_PKG_DIR = Path(__file__).resolve().parent
_HOOK_TEMPLATE = (_PKG_DIR.parent.parent / "hooks" / "post-commit")

SEGMENT_RE = re.compile(
    rf"{re.escape(MARKER)}.*?{re.escape(MARKER_END)}\n?",
    re.DOTALL,
)

_SEGMENT = f'''{MARKER}
RALLY_POINT_TOPLEVEL="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$RALLY_POINT_TOPLEVEL" ]; then
  echo "rally-point post-commit: cannot resolve repo toplevel" >&2
  exit 2
fi
RALLY_POINT_CAPTURE="$RALLY_POINT_TOPLEVEL/.git/hooks/.rally-point-capture.py"
if [ -f "$RALLY_POINT_CAPTURE" ]; then
  ( python3 "$RALLY_POINT_CAPTURE" >/dev/null 2>&1 ) </dev/null >/dev/null 2>&1 &
fi
{MARKER_END}
'''

# --- public-repo hygiene pre-commit ---
PRE_MARKER = "# --- BEGIN private-slug-guard pre-commit ---"
PRE_MARKER_END = "# --- END private-slug-guard pre-commit ---"

# Pinned guard scripts next to the hook resolve this plugin's guard
# implementations recorded at install time, so the hook works regardless
# of the committing tool's cwd or sys.path.
PRE_SEGMENT_RE = re.compile(
    rf"{re.escape(PRE_MARKER)}.*?{re.escape(PRE_MARKER_END)}\n?",
    re.DOTALL,
)

_PRE_SEGMENT = f'''{PRE_MARKER}
RALLY_POINT_TOPLEVEL="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$RALLY_POINT_TOPLEVEL" ]; then
  echo "private-slug-guard: cannot resolve repo toplevel — refusing to skip the guard" >&2
  exit 2
fi
PRIVATE_SLUG_GUARD="$RALLY_POINT_TOPLEVEL/.git/hooks/.private-slug-check.py"
if [ -f "$PRIVATE_SLUG_GUARD" ]; then
  python3 "$PRIVATE_SLUG_GUARD" || exit 1
fi
RUNTIME_MEMORY_GUARD="$RALLY_POINT_TOPLEVEL/.git/hooks/.runtime-memory-tracking-check.py"
if [ -f "$RUNTIME_MEMORY_GUARD" ]; then
  python3 "$RUNTIME_MEMORY_GUARD" || exit 1
fi
INDEPENDENT_AUDIT="$RALLY_POINT_TOPLEVEL/scripts/audit_before_commit.py"
if [ -f "$INDEPENDENT_AUDIT" ]; then
  python3 "$INDEPENDENT_AUDIT" || exit $?
fi
{PRE_MARKER_END}
'''

_PRE_GUARD_SRC = '''#!/usr/bin/env python3
"""Auto-generated by rally_point.install_git_hook — do not edit.

Run by .git/hooks/pre-commit. Delegates to the plugin's pinned
check_private_slugs.py; a non-zero exit aborts the commit.
"""
import runpy
import sys

_CHECKER = {checker!r}
sys.argv = [_CHECKER]
try:
    runpy.run_path(_CHECKER, run_name="__main__")
except SystemExit as exc:
    sys.exit(exc.code or 0)
'''

_RUNTIME_GUARD_SRC = '''#!/usr/bin/env python3
"""Auto-generated by rally_point.install_git_hook — do not edit.

Run by .git/hooks/pre-commit. Delegates to the plugin's pinned
check_runtime_memory_tracking.py; a non-zero exit aborts the commit.
A vanished checker (e.g. a pruned plugin cache) must not brick every
commit in the repo: warn and pass instead of crashing.
"""
import os
import runpy
import sys

_CHECKER = {checker!r}
if not os.path.isfile(_CHECKER):
    sys.stderr.write(
        "runtime-memory guard: checker missing at %s; skipping "
        "(re-run rally hook install to repin)\\n" % _CHECKER
    )
    sys.exit(0)
sys.argv = [_CHECKER]
try:
    runpy.run_path(_CHECKER, run_name="__main__")
except SystemExit as exc:
    sys.exit(exc.code or 0)
'''

_CAPTURE_SRC = '''#!/usr/bin/env python3
"""Auto-generated by rally_point.install_git_hook — do not edit.

Backgrounded by .git/hooks/post-commit. Fire-and-forget: any failure is
swallowed so a commit is never affected.
"""
import os
import subprocess
import sys

_PKG = {pkg!r}
if _PKG not in sys.path:
    sys.path.insert(0, _PKG)

MANIFEST_GLOBS = (
    "package.json", "package-lock.json", "pnpm-lock.yaml",
    "requirements.txt", "pyproject.toml", "uv.lock", "Cargo.toml",
    "go.mod", "Gemfile",
)


def _main():
    try:
        from post import post as _post
        # Discovery bridge: routes the hook's writes to the canonical
        # channel when policy=canonical (post-cutover state). The bridge
        # falls back to legacy on its own when discover() is unreachable,
        # so this import has no failure path that should suppress the
        # hook itself.
        from discovery_bridge import resolve as _bridge_resolve
    except Exception:
        return
    try:
        repo = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        # Route via bridge so canonical policy is honored. Falls back to
        # legacy when the bridge resolves via build-loop-internal.
        envelope = _bridge_resolve(repo)
        slug = envelope.app_slug
        from pathlib import Path as _Path
        chan = _Path(envelope.channel_dir)
        chan.mkdir(parents=True, exist_ok=True)
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        # --root makes the very first (parentless) commit list its
        # files too, otherwise diff-tree emits nothing for a root commit
        # and a first-commit manifest would never yield a dep-change.
        names = subprocess.run(
            ["git", "diff-tree", "--no-commit-id", "--name-only",
             "--root", "-r", "HEAD"],
            cwd=repo, capture_output=True, text=True, check=True,
        ).stdout.split()
        tool = (
            os.environ.get("RALLY_POINT_TOOL")
            or os.environ.get("APP_PULSE_TOOL")
            or "unknown"
        )
        model = (
            os.environ.get("RALLY_POINT_MODEL")
            or os.environ.get("APP_PULSE_MODEL")
            or "unknown"
        )
        run_id = (
            os.environ.get("RALLY_POINT_RUN_ID")
            or os.environ.get("APP_PULSE_RUN_ID")
            or "unknown"
        )
        _post(
            channel_dir=chan,
            kind="commit", tool=tool, model=model, run_id=run_id,
            app_slug=slug, payload={{"sha": sha, "files": names}},
            workdir=_Path(repo),
        )
        manifest_hits = sorted(
            n for n in names if os.path.basename(n) in MANIFEST_GLOBS
        )
        if manifest_hits:
            _post(
                channel_dir=chan,
                kind="dep-change", tool=tool, model=model, run_id=run_id,
                app_slug=slug,
                payload={{"sha": sha, "manifests": manifest_hits}},
                workdir=_Path(repo),
            )
    except Exception:
        return


if __name__ == "__main__":
    _main()
'''


def _is_git_repo(repo: Path) -> bool:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=str(repo), capture_output=True, text=True, check=True,
        ).stdout.strip()
        return bool(out)
    except (subprocess.CalledProcessError, OSError):
        return False


def _git_hooks_dir(repo: Path) -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--git-path", "hooks"],
        cwd=str(repo), capture_output=True, text=True, check=True,
    ).stdout.strip()
    p = Path(out)
    return p if p.is_absolute() else (Path(repo) / p)


def _make_executable(path: Path) -> None:
    st = os.stat(path)
    path.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _install_post_commit(hooks_dir: Path) -> None:
    """Install/chain the post-commit capture. Idempotent."""
    # The pinned capture script (rewritten each install — cheap, keeps
    # the package path current if the plugin moved).
    capture = hooks_dir / ".rally-point-capture.py"
    capture.write_text(_CAPTURE_SRC.format(pkg=str(_PKG_DIR)))
    capture.chmod(0o755)

    hook = hooks_dir / "post-commit"
    if not hook.exists():
        hook.write_text("#!/bin/sh\n" + _SEGMENT + "exit 0\n")
    else:
        body = hook.read_text()
        if MARKER in body:
            # Re-install: replace our segment in place so the pinned
            # capture wiring stays current if the plugin moved or the
            # segment template changed.
            hook.write_text(SEGMENT_RE.sub(_SEGMENT, body))
            _make_executable(hook)
            return
        if LEGACY_MARKER in body:
            hook.write_text(LEGACY_SEGMENT_RE.sub(_SEGMENT, body))
            _make_executable(hook)
            return
        # Preserve the existing hook verbatim; append our segment.
        if not body.endswith("\n"):
            body += "\n"
        hook.write_text(body + "\n" + _SEGMENT)
    _make_executable(hook)


def _repo_has_slug_denylist(hooks_dir: Path) -> bool:
    """Can check_private_slugs.py actually run in this repo?

    It needs a ``.private-slugs`` denylist at the repo root. Absent one it
    exits 2 and blocks every commit; an empty one is rejected as well, so
    there is no way to install it passively. ``.private-slugs.example``
    counts: a repo that ships the template has opted into the guard and only
    needs the operator to fill it in.
    """
    root = hooks_dir.parent.parent  # <repo>/.git/hooks -> <repo>
    return (root / ".private-slugs").exists() or (root / ".private-slugs.example").exists()


def _install_pre_commit(hooks_dir: Path) -> None:
    """Install/chain the public-repo hygiene pre-commit. Idempotent.

    The guard MUST be able to abort a commit, so (unlike post-commit)
    its segment exits non-zero on a hit. When chaining onto an existing
    pre-commit, the guard segment is appended last so a prior hook's
    own checks still run first.

    On re-install when our segment is already present, the segment is
    REPLACED in place (not early-returned). The segment text carries the
    pinned guard wiring; a re-install after the plugin moved, or after
    the segment template changed, must refresh it — early-returning
    would leave a stale segment that can silently disable the guard.
    """
    private_checker = _PKG_DIR.parent / "check_private_slugs.py"
    runtime_checker = _PKG_DIR.parent / "check_runtime_memory_tracking.py"
    if not private_checker.exists() and not runtime_checker.exists():
        return  # nothing to guard with — skip silently
    guard = hooks_dir / ".private-slug-check.py"
    if private_checker.exists() and _repo_has_slug_denylist(hooks_dir):
        guard.write_text(_PRE_GUARD_SRC.format(checker=str(private_checker)))
        guard.chmod(0o755)
    else:
        # Self-heal: a previous install may have left a guard that can only
        # exit 2. The generated segment is defensive (`if [ -f ... ]`), so
        # removing the file disables the check cleanly and leaves every other
        # guard in the segment running.
        guard.unlink(missing_ok=True)
    if runtime_checker.exists():
        # Pin the shim to a LOCAL copy of the checker under .git/hooks, not to
        # the plugin/package path: plugin caches get pruned (observed twice on
        # 2026-08-28, bricking every commit in a consumer repo), while a copy
        # inside .git/hooks lives exactly as long as the hooks that call it.
        # The checker is stdlib-only and self-contained, so a copy is safe.
        local_checker = hooks_dir / ".runtime-memory-checker.py"
        local_checker.write_text(runtime_checker.read_text())
        local_checker.chmod(0o755)
        guard = hooks_dir / ".runtime-memory-tracking-check.py"
        guard.write_text(_RUNTIME_GUARD_SRC.format(checker=str(local_checker)))
        guard.chmod(0o755)

    hook = hooks_dir / "pre-commit"
    if not hook.exists():
        hook.write_text("#!/bin/sh\n" + _PRE_SEGMENT + "exit 0\n")
    else:
        body = hook.read_text()
        if PRE_MARKER in body:
            # Re-install: replace our (possibly stale) segment in place
            # so the pinned guard wiring is always current.
            hook.write_text(PRE_SEGMENT_RE.sub(_PRE_SEGMENT, body))
            _make_executable(hook)
            return
        if not body.endswith("\n"):
            body += "\n"
        hook.write_text(body + "\n" + _PRE_SEGMENT)
    _make_executable(hook)


def install(repo: Path) -> bool:
    """Install/chain both git hooks in ``repo``. Idempotent.

    Returns True on success, False if ``repo`` is not a git repo.
    """
    repo = Path(repo)
    if not _is_git_repo(repo):
        return False
    hooks_dir = _git_hooks_dir(repo)
    hooks_dir.mkdir(parents=True, exist_ok=True)
    _install_post_commit(hooks_dir)
    _install_pre_commit(hooks_dir)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="Git repository to update.")
    args = parser.parse_args(argv)
    return 0 if install(Path(args.repo).resolve()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
