#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""report — markdown report rendering, candidate building, outcomes JSONL appender."""
from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Any

from .session import TEST_CATEGORIES


def render_report(
    *,
    window_label: str,
    sessions_scanned: int,
    sessions_in_window: int,
    corrections: list[dict[str, Any]],
    sequences: list[dict[str, Any]],
    cross_files: list[dict[str, Any]],
    churn_files: list[dict[str, Any]],
    rituals: list[dict[str, Any]],
    secrets: list[dict[str, Any]],
    test_table: list[dict[str, Any]],
    test_invocation_count: int,
    test_outcomes_jsonl_path: Path,
    generated_at: dt.datetime,
) -> str:
    lines: list[str] = []
    lines.append(f"# Transcript Pattern Miner — {generated_at.date().isoformat()}")
    lines.append("")
    lines.append(f"- Window: **{window_label}**")
    lines.append(f"- Session files scanned: {sessions_scanned}")
    lines.append(f"- Session files in window: {sessions_in_window}")
    lines.append(f"- Generated: {generated_at.isoformat(timespec='seconds')}")
    lines.append("")
    lines.append("> Pure-stdlib pattern miner. Single-user context: full quotes (≤300 chars) and full secret values surfaced for rotation tracking.")
    lines.append("> Output remains local-only — no network egress, no auto-publish.")
    lines.append("")

    _render_corrections(lines, corrections)
    _render_sequences(lines, sequences)
    _render_cross_project(lines, cross_files, churn_files)
    _render_rituals(lines, rituals)
    _render_secrets(lines, secrets)
    _render_test_outcomes(lines, test_table, test_invocation_count, test_outcomes_jsonl_path)

    lines.append("---")
    lines.append("Generated by `transcript-pattern-miner.py`. No network. No LLM. Local stdlib only.")
    return "\n".join(lines)


def _render_corrections(lines: list[str], corrections: list[dict[str, Any]]) -> None:
    lines.append("## 1. Recurring user corrections")
    lines.append("")
    if not corrections:
        lines.append("_No clusters with 3+ occurrences found._")
    else:
        lines.append(f"_{len(corrections)} cluster(s) with 3+ occurrences. Highest-signal candidate for `feedback_*.md`._")
        lines.append("")
        lines.append("| Count | First seen | Last seen | Projects | Representative quote |")
        lines.append("|---:|---|---|---|---|")
        for c in corrections[:15]:
            projs = ", ".join(c["projects"][:3])
            if len(c["projects"]) > 3:
                projs += f", +{len(c['projects']) - 3}"
            quote = c["representative_quote"].replace("|", "\\|")
            lines.append(f"| {c['count']} | {c['first_seen'] or '?'} | {c['last_seen'] or '?'} | {projs} | {quote} |")
    lines.append("")


def _render_sequences(lines: list[str], sequences: list[dict[str, Any]]) -> None:
    lines.append("## 2. Repeated tool sequences")
    lines.append("")
    if not sequences:
        lines.append("_No sequences (length 3-6) recurring in 3+ sessions._")
    else:
        lines.append(f"_Top {min(len(sequences), 10)} sequences. Candidate workflow/skill targets._")
        lines.append("")
        lines.append("| Sessions | Length | Sequence |")
        lines.append("|---:|---:|---|")
        for s in sequences[:10]:
            seq = " → ".join(s["sequence"])
            lines.append(f"| {s['session_count']} | {len(s['sequence'])} | `{seq}` |")
    lines.append("")


def _render_cross_project(
    lines: list[str],
    cross_files: list[dict[str, Any]],
    churn_files: list[dict[str, Any]],
) -> None:
    lines.append("## 3. Cross-project file patterns")
    lines.append("")
    if cross_files:
        lines.append("_Files touched in 3+ projects (shared template / utility)._")
        lines.append("")
        lines.append("| Projects | File |")
        lines.append("|---:|---|")
        for f in cross_files[:10]:
            lines.append(f"| {f['project_count']} | `{f['file']}` |")
    else:
        lines.append("_No cross-project file patterns found._")
    lines.append("")
    if churn_files:
        lines.append("_Within-project churn (5+ touches in one project)._")
        lines.append("")
        lines.append("| Touches | Project | File |")
        lines.append("|---:|---|---|")
        for f in churn_files[:10]:
            lines.append(f"| {f['touches']} | {f['project']} | `{f['file']}` |")
        lines.append("")


def _render_rituals(lines: list[str], rituals: list[dict[str, Any]]) -> None:
    lines.append("## 4. Manual command rituals")
    lines.append("")
    if not rituals:
        lines.append("_No bash command shapes repeating 5+ times._")
    else:
        lines.append(f"_Top {min(len(rituals), 10)} repeating shell shapes. Candidates for `/schedule` or scripts._")
        lines.append("")
        lines.append("| Count | Sessions | Shape |")
        lines.append("|---:|---:|---|")
        for r in rituals[:10]:
            shape = r["command_shape"].replace("|", "\\|")
            lines.append(f"| {r['count']} | {r['session_count']} | `{shape}` |")
    lines.append("")


def _render_secrets(lines: list[str], secrets: list[dict[str, Any]]) -> None:
    lines.append("## 5. Secrets observed (rotation tracker)")
    lines.append("")
    if not secrets:
        lines.append("_No secrets matched the detector regex set in this window._")
    else:
        lines.append(f"_{len(secrets)} distinct secret value(s) observed — full values surfaced for rotation. **Rotate any real keys before doing anything else with this report.**_")
        lines.append("")
        lines.append("| Kind | Preview | First seen | Last seen | Sessions | Projects |")
        lines.append("|---|---|---|---|---:|---|")
        for s in secrets[:50]:
            projs = ", ".join(s["projects"][:3])
            if len(s["projects"]) > 3:
                projs += f", +{len(s['projects']) - 3}"
            lines.append(
                f"| {s['kind']} | `{s['preview']}` | {s['first_seen'] or '?'} | "
                f"{s['last_seen'] or '?'} | {s['session_count']} | {projs} |"
            )
    lines.append("")
    lines.append(
        "> Full secret values are NOT in this report. To verify rotation, "
        "re-find the value in the source JSONL by `session_id` + date. "
        "Report safety: previews here are 12 chars and not sufficient to authenticate."
    )
    lines.append("")


def _render_test_outcomes(
    lines: list[str],
    test_table: list[dict[str, Any]],
    test_invocation_count: int,
    test_outcomes_jsonl_path: Path,
) -> None:
    lines.append("## 6. Test patterns + outcomes")
    lines.append("")
    lines.append(
        "_Per research entry tools.testing-prioritization-llm-and-ui-2026-05-01.md §4.2._"
    )
    lines.append(
        f"_Total test invocations detected: {test_invocation_count}. "
        f"Per-invocation log appended to `{test_outcomes_jsonl_path}`._"
    )
    lines.append("")
    if not test_table:
        lines.append("_No test invocations matched the 8 detector categories in this window._")
    else:
        lines.append("Categories: A=IBR · B=runner (pytest/jest/vitest) · C=validation-gate prose · D=synthetic fixture · E=smoke (curl -s) · F=real-data regression · G=manual visual · H=type/lint")
        lines.append("")
        lines.append("| Category | Count | POSITIVE | MIXED | REWORK | NO_SIGNAL | Top project |")
        lines.append("|---|---:|---:|---:|---:|---:|---|")
        for r in test_table:
            lines.append(
                f"| {r['category']} | {r['count']} | {r['POSITIVE']} | {r['MIXED']} | "
                f"{r['REWORK']} | {r['NO_SIGNAL']} | {r['top_project']} |"
            )
        lines.append("")
        lines.append(
            "> Outcome inference combines (a) tool_result is_error status when the test was a tool call "
            "and (b) implicit acceptance/correction signals on the next 1-3 user messages. "
            "MIXED = tool succeeded but no follow-up user signal (could be silent acceptance OR session ended). "
            "NO_SIGNAL = neither tool-result nor next-user signal was conclusive. "
            "REWORK/POSITIVE rows where the only evidence is user-text (no is_error basis) are marked "
            "`directional_only=true` in .outcomes.jsonl — treat those counts as directional, not hard metrics."
        )
    lines.append("")


def build_candidates(
    corrections: list[dict[str, Any]],
    sequences: list[dict[str, Any]],
    rituals: list[dict[str, Any]],
    cross_files: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Top-5 ranked candidate proposals for self-improvement-architect to consume."""
    candidates: list[dict[str, Any]] = []
    for c in corrections[:3]:
        candidates.append({
            "kind": "feedback_candidate",
            "shape": "user_correction_cluster",
            "count": c["count"],
            "last_seen": c["last_seen"],
            "representative_quote": c["representative_quote"],
            "projects": c["projects"],
            "rationale": "Repeated user correction — highest signal for a feedback_*.md note.",
        })
    for s in sequences[:2]:
        candidates.append({
            "kind": "skill_or_workflow_candidate",
            "shape": "repeated_tool_sequence",
            "session_count": s["session_count"],
            "sequence": s["sequence"],
            "rationale": "Tool sequence recurring across 3+ sessions — candidate workflow/skill.",
        })
    for r in rituals[:1]:
        candidates.append({
            "kind": "automation_candidate",
            "shape": "bash_ritual",
            "count": r["count"],
            "command_shape": r["command_shape"],
            "rationale": "Shell shape repeated 5+ times — candidate for /schedule or script.",
        })
    for f in cross_files[:1]:
        candidates.append({
            "kind": "shared_utility_candidate",
            "shape": "cross_project_file",
            "project_count": f["project_count"],
            "file": f["file"],
            "rationale": "File touched in 3+ projects — candidate for shared template or utility.",
        })
    return candidates[:5]


def append_outcomes_jsonl(path: Path, rows: list[dict[str, Any]]) -> int:
    """Append outcome rows to the JSONL file. Returns count written."""
    if not rows:
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    with path.open("a", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
            written += 1
    return written
