#!/usr/bin/env python3
"""Idempotent installer for the App Pulse git post-commit capture.

Installs (or chains) ``.git/hooks/post-commit`` in a consumer repo so a
commit by ANY tool emits a ``commit`` (and, for manifest changes, a
``dep-change``) record + bumps the channel revision.

Contract:
  - only operates inside a git repo (``.git`` present);
  - idempotent: re-running makes no further change (marker-guarded);
  - never clobbers a pre-existing post-commit — the App Pulse segment is
    appended/chained, unrelated content is preserved verbatim;
  - the hook body is fire-and-forget (it backgrounds the capture and
    ``exit 0`` so a commit can never be slowed or failed).

The capture logic is written next to the hook as a self-contained
``.git/hooks/.app-pulse-capture.py`` that pins the absolute path of
*this* plugin's ``scripts/app_pulse`` package (recorded at install
time), so the hook keeps working regardless of the committing tool's
cwd or sys.path.
"""
from __future__ import annotations

import os
import stat
import subprocess
from pathlib import Path

MARKER = "# --- BEGIN app-pulse post-commit ---"
MARKER_END = "# --- END app-pulse post-commit ---"

_PKG_DIR = Path(__file__).resolve().parent
_HOOK_TEMPLATE = (_PKG_DIR.parent.parent / "hooks" / "post-commit")

_SEGMENT = f'''{MARKER}
APP_PULSE_CAPTURE="$(git rev-parse --show-toplevel 2>/dev/null)/.git/hooks/.app-pulse-capture.py"
if [ -f "$APP_PULSE_CAPTURE" ]; then
  ( python3 "$APP_PULSE_CAPTURE" >/dev/null 2>&1 ) </dev/null >/dev/null 2>&1 &
fi
{MARKER_END}
'''

_CAPTURE_SRC = '''#!/usr/bin/env python3
"""Auto-generated by app_pulse.install_git_hook — do not edit.

Backgrounded by .git/hooks/post-commit. Fire-and-forget: any failure is
swallowed so a commit is never affected.
"""
import os
import subprocess
import sys

_PKG = {pkg!r}
if _PKG not in sys.path:
    sys.path.insert(0, _PKG)

MANIFEST_GLOBS = (
    "package.json", "package-lock.json", "pnpm-lock.yaml",
    "requirements.txt", "pyproject.toml", "uv.lock", "Cargo.toml",
    "go.mod", "Gemfile",
)


def _main():
    try:
        import channel_paths as ap
        import changes as ch
        import revision as rev
    except Exception:
        return
    try:
        repo = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        slug = ap.app_slug(cwd=repo)
        chan = ap.ensure_channel_dir(slug)
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        # --root makes the very first (parentless) commit list its
        # files too, otherwise diff-tree emits nothing for a root commit
        # and a first-commit manifest would never yield a dep-change.
        names = subprocess.run(
            ["git", "diff-tree", "--no-commit-id", "--name-only",
             "--root", "-r", "HEAD"],
            cwd=repo, capture_output=True, text=True, check=True,
        ).stdout.split()
        tool = os.environ.get("APP_PULSE_TOOL", "unknown")
        model = os.environ.get("APP_PULSE_MODEL", "unknown")
        run_id = os.environ.get("APP_PULSE_RUN_ID", "unknown")
        ch.append_change(chan, ch.make_record(
            kind="commit", tool=tool, model=model, run_id=run_id,
            app_slug=slug, payload={{"sha": sha, "files": names}},
            revision=rev.read_revision(chan) + 1,
        ))
        manifest_hits = sorted(
            n for n in names if os.path.basename(n) in MANIFEST_GLOBS
        )
        if manifest_hits:
            ch.append_change(chan, ch.make_record(
                kind="dep-change", tool=tool, model=model, run_id=run_id,
                app_slug=slug,
                payload={{"sha": sha, "manifests": manifest_hits}},
                revision=rev.read_revision(chan) + 1,
            ))
        rev.bump_revision(chan)
    except Exception:
        return


if __name__ == "__main__":
    _main()
'''


def _is_git_repo(repo: Path) -> bool:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=str(repo), capture_output=True, text=True, check=True,
        ).stdout.strip()
        return bool(out)
    except (subprocess.CalledProcessError, OSError):
        return False


def _git_dir(repo: Path) -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=str(repo), capture_output=True, text=True, check=True,
    ).stdout.strip()
    p = Path(out)
    return p if p.is_absolute() else (Path(repo) / p)


def install(repo: Path) -> bool:
    """Install/chain the post-commit hook in ``repo``. Idempotent.

    Returns True on success, False if ``repo`` is not a git repo.
    """
    repo = Path(repo)
    if not _is_git_repo(repo):
        return False
    hooks_dir = _git_dir(repo) / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    # The pinned capture script (rewritten each install — cheap, keeps
    # the package path current if the plugin moved).
    capture = hooks_dir / ".app-pulse-capture.py"
    capture.write_text(_CAPTURE_SRC.format(pkg=str(_PKG_DIR)))
    capture.chmod(0o755)

    hook = hooks_dir / "post-commit"
    if not hook.exists():
        hook.write_text("#!/bin/sh\n" + _SEGMENT + "exit 0\n")
    else:
        body = hook.read_text()
        if MARKER in body:
            return True  # idempotent: our segment already chained
        # Preserve the existing hook verbatim; append our segment.
        if not body.endswith("\n"):
            body += "\n"
        hook.write_text(body + "\n" + _SEGMENT)
    st = os.stat(hook)
    hook.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return True
