#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""Single definition of "generated artifact" for the self-review pipeline.

A commit hook regenerates several files on EVERY commit and re-stages them.
Churn is measured over a rolling window, so those files always sit at the top
of any churn ranking — a false positive by construction, not a code defect.
Measured cost before this existed: 180 of 1,233 queued proposals were this one
class.

Both the producer (`efficiency.scan_churn`) and the consumer
(`drain_self_review_proposals`) need the same answer to "is this a build
product?". They previously each carried their own idea of it, which is exactly
how the two drift apart. This module is the one place that decides.

Matching is SUBSTRING, not path equality, because the two callers hold
different shapes: the producer has a clean repo-relative path from `git log`,
while the drain has a free-text finding blob with the path quoted inside it.
Substring matching is the only predicate that answers both without either
caller reformatting its input.
"""
from __future__ import annotations

# Build products regenerated by tooling, never authored by hand. A finding
# about any of these is noise regardless of which detector emitted it.
GENERATED_PATH_HINTS: tuple[str, ...] = (
    "architecture/model.json",
    "architecture/ARCHITECTURE.md",
    "docs/build-loop-flow-mockup.html",
    "INDEX.md",
    "INDEX.jsonl",
    ".build-loop/",
)


def matched_generated_hint(text: str) -> str | None:
    """Return the hint that marks `text` as a generated artifact, else None.

    Returns the matched hint rather than a bare bool so callers can name the
    reason in their output instead of re-deriving it.
    """
    if not text:
        return None
    for hint in GENERATED_PATH_HINTS:
        if hint in text:
            return hint
    return None


def is_generated_path(text: str) -> bool:
    """True when `text` names a build product rather than authored source."""
    return matched_generated_hint(text) is not None
