#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""Build the slim Codex plugin artifact.

The source repo keeps Claude's full internal skill tree at ``skills/``. Codex
auto-discovers root ``skills/*/SKILL.md`` entries, so the Codex marketplace must
install from an artifact that exposes exactly one public skill.
"""
from __future__ import annotations

import argparse
import filecmp
import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import Iterable


DEFAULT_TARGET = Path("plugin-artifacts/codex")
IGNORED_NAMES = {".DS_Store", "__pycache__", ".pytest_cache"}
IGNORED_SUFFIXES = {".pyc"}
TOP_LEVEL_FILES = ("AGENTS.md", "README.md", "LICENSE")


class ArtifactError(RuntimeError):
    pass


def ignore_generated(_dir: str, names: list[str]) -> set[str]:
    ignored = set()
    for name in names:
        if name in IGNORED_NAMES:
            ignored.add(name)
            continue
        if any(name.endswith(suffix) for suffix in IGNORED_SUFFIXES):
            ignored.add(name)
    return ignored


def copy_file(source: Path, target: Path) -> None:
    if not source.is_file():
        raise ArtifactError(f"missing required file: {source}")
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def copy_tree(source: Path, target: Path) -> None:
    if not source.is_dir():
        raise ArtifactError(f"missing required directory: {source}")
    shutil.copytree(source, target, ignore=ignore_generated)


def write_codex_manifest(source: Path, target: Path) -> None:
    manifest_path = source / ".codex-plugin" / "plugin.json"
    if not manifest_path.is_file():
        raise ArtifactError(f"missing required file: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["skills"] = "./skills"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def write_notice(target: Path) -> None:
    target.write_text(
        "\n".join(
            [
                "# Codex Build Loop Artifact",
                "",
                "Generated by `python3 scripts/build_codex_plugin_artifact.py`.",
                "This artifact is the Codex marketplace install surface.",
                "It exposes exactly one public skill: `build-loop`.",
                "",
            ]
        ),
        encoding="utf-8",
    )


def skill_files(root: Path) -> list[Path]:
    return sorted(root.rglob("SKILL.md"))


def validate_artifact(target: Path) -> None:
    manifest_path = target / ".codex-plugin" / "plugin.json"
    skills_root = target / "skills"
    if not manifest_path.is_file():
        raise ArtifactError(f"artifact missing {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("skills") != "./skills":
        raise ArtifactError("artifact Codex manifest must use skills=./skills")

    files = skill_files(skills_root)
    rel_files = [str(path.relative_to(target)) for path in files]
    if rel_files != ["skills/build-loop/SKILL.md"]:
        raise ArtifactError(f"artifact must expose exactly one SKILL.md, got {rel_files}")


def build_artifact(source: Path, target: Path) -> None:
    source = source.resolve()
    target = target.resolve()
    if source == target or target in source.parents:
        raise ArtifactError(f"refusing to write artifact above source: {target}")

    parent = target.parent
    parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".codex-artifact-", dir=str(parent)) as tmp_raw:
        tmp = Path(tmp_raw)
        write_codex_manifest(source, tmp / ".codex-plugin" / "plugin.json")
        for name in TOP_LEVEL_FILES:
            copy_file(source / name, tmp / name)
        copy_tree(source / "skills" / "build-loop", tmp / "skills" / "build-loop")
        copy_file(source / "docs" / "agent-surface-policy.md", tmp / "docs" / "agent-surface-policy.md")
        write_notice(tmp / "BUILD-ARTIFACT.md")
        validate_artifact(tmp)

        if target.exists():
            shutil.rmtree(target)
        os.replace(tmp, target)


def iter_files(root: Path) -> Iterable[Path]:
    for path in sorted(root.rglob("*")):
        if path.is_file():
            yield path


def assert_same_tree(expected: Path, actual: Path) -> None:
    expected_files = {path.relative_to(expected) for path in iter_files(expected)}
    actual_files = {path.relative_to(actual) for path in iter_files(actual)}
    if expected_files != actual_files:
        missing = sorted(str(path) for path in expected_files - actual_files)
        extra = sorted(str(path) for path in actual_files - expected_files)
        raise ArtifactError(f"artifact file set differs; missing={missing}, extra={extra}")
    for rel in sorted(expected_files):
        if not filecmp.cmp(expected / rel, actual / rel, shallow=False):
            raise ArtifactError(f"artifact file differs: {rel}")


def check_artifact(source: Path, target: Path) -> None:
    parent = target.resolve().parent
    parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".codex-artifact-check-", dir=str(parent)) as tmp_raw:
        tmp = Path(tmp_raw) / "codex"
        build_artifact(source, tmp)
        assert_same_tree(tmp, target.resolve())
    validate_artifact(target.resolve())


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=".", help="Build Loop source repo root.")
    parser.add_argument("--target", default=str(DEFAULT_TARGET), help="Codex artifact output directory.")
    parser.add_argument("--check", action="store_true", help="Fail if the artifact is missing or stale.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    source = Path(args.source).expanduser().resolve()
    target = Path(args.target).expanduser()
    if not target.is_absolute():
        target = source / target
    try:
        if args.check:
            check_artifact(source, target)
            print(f"codex artifact up to date: {target}")
        else:
            build_artifact(source, target)
            print(f"codex artifact written: {target}")
        return 0
    except ArtifactError as exc:
        print(f"error: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
