#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""Regenerate `.episodic/decisions/INDEX.md` and `.episodic/issues/INDEX.md`.

Frontmatter-rollup index per design §2/§4. Defaults to filtering on
`confidence >= confirmed`; pass `--confidence-floor` to widen.

Contract:
  stdout      -> nothing on success
  stderr      -> log lines
  exit 0      -> success
  exit 1      -> validation error (bad workdir, malformed frontmatter)
  exit 2      -> filesystem error
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Reuse the writer's helpers — same parser, same atomic write.
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from write_decision import (  # type: ignore  # noqa: E402
    CONFIDENCE_ORDER,
    atomic_write_bytes,
    parse_frontmatter,
    regenerate_index,
)


def list_decisions(decisions_dir: Path):
    if not decisions_dir.exists():
        return []
    return sorted(decisions_dir.glob("[0-9][0-9][0-9][0-9]-*.md"))


def list_issues(issues_dir: Path):
    if not issues_dir.exists():
        return []
    return sorted(p for p in issues_dir.glob("*.md") if p.name != "INDEX.md")


def regenerate_issues_index(issues_dir: Path) -> None:
    rows = []
    for f in list_issues(issues_dir):
        fm = parse_frontmatter(f.read_text(encoding="utf-8")) or {}
        rows.append((str(fm.get("date", f.stem)), fm, f))
    rows.sort(key=lambda r: r[0])
    lines = [
        "# Issues — INDEX",
        "",
        "_Auto-generated by `scripts/regenerate_knowledge_index.py`._",
        "",
        "| date | title | status | tags |",
        "|---|---|---|---|",
    ]
    for date, fm, f in rows:
        tag_str = ",".join(fm.get("tags", []) or [])
        lines.append(
            f"| {date} | [{fm.get('title', f.stem)}]({f.name}) | "
            f"{fm.get('status', 'open')} | {tag_str} |"
        )
    if not rows:
        lines.append("| _(no issues)_ |  |  |  |")
    out = "\n".join(lines) + "\n"
    atomic_write_bytes(issues_dir / "INDEX.md", out.encode("utf-8"))


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Regenerate decision + issue INDEX.md")
    p.add_argument("--workdir", default=".", help="Project root")
    p.add_argument(
        "--confidence-floor",
        default="confirmed",
        choices=sorted(CONFIDENCE_ORDER),
        help="Decisions: minimum confidence to include in INDEX",
    )
    args = p.parse_args(argv)

    workdir = Path(args.workdir).resolve()
    HERE_LOCAL = Path(__file__).resolve().parent
    import sys as _sys
    if str(HERE_LOCAL) not in _sys.path:
        _sys.path.insert(0, str(HERE_LOCAL))
    from _paths import legacy_decisions_dir  # noqa: PLC0415
    decisions_dir = legacy_decisions_dir(workdir)
    issues_dir = workdir / ".episodic" / "issues"

    if not decisions_dir.exists() and not issues_dir.exists():
        print(f"validation error: neither {decisions_dir} nor {issues_dir} exists", file=sys.stderr)
        return 1

    try:
        if decisions_dir.exists():
            regenerate_index(decisions_dir, confidence_floor=args.confidence_floor)
            print(f"regenerated {decisions_dir / 'INDEX.md'}", file=sys.stderr)
        if issues_dir.exists():
            regenerate_issues_index(issues_dir)
            print(f"regenerated {issues_dir / 'INDEX.md'}", file=sys.stderr)
    except OSError as e:
        print(f"filesystem error: {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
