#!/usr/bin/env python3
"""Consumer for the self-review proposal queue.

The queue had no consumer. `self-review` emitted findings on every run and
nothing ever retired them, so `.build-loop/proposals/` grew to 1,261 files
holding ~560 distinct findings. A producer with no consumer is the root cause;
this is the consumer.

Four stages, in order:

  1. DEDUPE      collapse re-emissions of the same finding (measured 2.2x
                 overall, 5.9x on missing-test findings)
  2. REVALIDATE  drop findings that were true once and are not true now
                 (test since written, source script deleted)
  3. FILTER      drop classes that are not actionable by construction, e.g.
                 churn on generated artifacts a commit hook regenerates
  4. ROUTE       bucket the survivors by what should happen to them

Read-only by default. `--archive` moves superseded files to
`.build-loop/proposals/archive/<date>/` — it never deletes.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from collections import defaultdict
from pathlib import Path

FINDING_RE = re.compile(r"^## Finding:\s*(.+?)\s*$", re.MULTILINE)
KIND_RE = re.compile(r"^\*\*Kind\*\*:\s*`([^`]+)`", re.MULTILINE)
SEVERITY_RE = re.compile(r"^severity:\s*(\S+)", re.MULTILINE)
CLASSIFY_RE = re.compile(r"^classify_hint:\s*(\S+)", re.MULTILINE)
CREATED_RE = re.compile(r"^created_ts:\s*(\S+)", re.MULTILINE)
EXPECTED_TEST_RE = re.compile(r"expected_test='([^']+)'")
SCRIPT_RE = re.compile(r"script='([^']+)'")
PATH_IN_TITLE_RE = re.compile(r"'([^']+)'")

# Not actionable by construction. Churn is measured over a rolling 7-day
# window, so a generated artifact regenerated by a commit hook always looks
# like a hot spot. Reporting that as a defect is a false positive every time.
NON_ACTIONABLE_KINDS = {"high_churn_file"}

# Findings about build products are noise regardless of kind. The definition
# lives in one place because the PRODUCER (self_review.efficiency.scan_churn)
# now suppresses the same class at emission; two copies of this list would
# drift and reopen the false-positive queue from the producer side.
from self_review.generated_paths import (  # noqa: E402
    GENERATED_PATH_HINTS,
    matched_generated_hint,
)

# Findings that are not code fixes at all. They belong in memory or in the
# skill-authoring lifecycle, and routing them to an implementer wastes a run.
MEMORY_ROUTED_KINDS = {"user_correction_cluster"}
SKILL_ROUTED_KINDS = {"bash_ritual_candidate"}


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _first(pattern: re.Pattern, text: str, default: str = "") -> str:
    m = pattern.search(text)
    return m.group(1) if m else default


def parse_proposal(path: Path) -> dict:
    text = _read(path)
    return {
        "path": path,
        "finding": _first(FINDING_RE, text, path.stem),
        "kind": _first(KIND_RE, text, "unknown"),
        "severity": _first(SEVERITY_RE, text, "UNKNOWN"),
        "classify": _first(CLASSIFY_RE, text, "UNKNOWN"),
        "created": _first(CREATED_RE, text, ""),
        "expected_test": _first(EXPECTED_TEST_RE, text),
        "script": _first(SCRIPT_RE, text),
        "text": text,
    }


def identity(p: dict) -> str:
    """Stable key for 'the same finding'.

    Keyed on kind + finding title. Two runs flagging the same untested script
    produce identical titles, which is what makes the collapse safe.
    """
    return f"{p['kind']}::{p['finding']}"


def is_stale(p: dict) -> tuple[bool, str]:
    """True when the finding was valid once but is not valid now."""
    if p["kind"] == "self_missing_test":
        expected = p.get("expected_test")
        script = p.get("script")
        if expected and Path(expected).exists():
            return True, "test now exists"
        if script and not Path(script).exists():
            return True, "source script deleted"
    # A finding naming a path that no longer exists cannot be acted on.
    if p["kind"] in {"self_oversized_file", "self_complexity_high_complexity"}:
        m = PATH_IN_TITLE_RE.search(p["finding"])
        if m:
            candidate = m.group(1)
            if "/" in candidate and not Path(candidate).exists():
                return True, "target path no longer exists"
    return False, ""


def is_non_actionable(p: dict) -> tuple[bool, str]:
    if p["kind"] in NON_ACTIONABLE_KINDS:
        return True, f"{p['kind']} is advisory-only (rolling-window churn)"
    script = str(p.get("script", ""))
    marker = "/.build-loop/worktrees/"
    if marker in script:
        worktree_relative = script.split(marker, 1)[1]
        script = worktree_relative.split("/", 1)[1] if "/" in worktree_relative else script
    blob = f"{p['finding']} {script}"
    hint = matched_generated_hint(blob)
    if hint:
        return True, f"target is a generated artifact ({hint})"
    return False, ""


def route(p: dict) -> str:
    if p["kind"] in MEMORY_ROUTED_KINDS:
        return "memory"
    if p["kind"] in SKILL_ROUTED_KINDS:
        return "skill-candidate"
    if p["kind"] == "self_missing_test" and p["classify"] == "SAFE":
        return "auto-fixable"
    if p["classify"] == "SAFE":
        return "safe-review"
    return "needs-judgment"


def drain(proposals_dir: Path) -> dict:
    files = sorted(p for p in proposals_dir.glob("*.md") if p.is_file())
    parsed = [parse_proposal(p) for p in files]

    groups: dict[str, list[dict]] = defaultdict(list)
    for p in parsed:
        groups[identity(p)].append(p)

    kept, superseded, stale, non_actionable = [], [], [], []
    for _key, group in groups.items():
        group.sort(key=lambda g: g["created"] or "")
        newest, older = group[-1], group[:-1]
        superseded.extend(older)

        gone, why = is_stale(newest)
        if gone:
            newest = {**newest, "reason": why}
            stale.append(newest)
            continue
        noise, why = is_non_actionable(newest)
        if noise:
            newest = {**newest, "reason": why}
            non_actionable.append(newest)
            continue
        kept.append(newest)

    buckets: dict[str, list[dict]] = defaultdict(list)
    for p in kept:
        buckets[route(p)].append(p)

    return {
        "total_files": len(files),
        "unique_findings": len(groups),
        "superseded": superseded,
        "stale": stale,
        "non_actionable": non_actionable,
        "actionable": kept,
        "buckets": {k: v for k, v in buckets.items()},
    }


def archive(result: dict, proposals_dir: Path, stamp: str) -> int:
    dest_root = proposals_dir / "archive" / stamp
    moved = 0
    for label in ("superseded", "stale", "non_actionable"):
        dest = dest_root / label
        dest.mkdir(parents=True, exist_ok=True)
        for p in result[label]:
            src = p["path"]
            if not src.exists():
                continue
            shutil.move(str(src), str(dest / src.name))
            moved += 1
    return moved


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workdir", default=os.getcwd())
    ap.add_argument("--archive", action="store_true",
                    help="move superseded/stale/non-actionable files to archive/ (never deletes)")
    ap.add_argument("--stamp", default="drain",
                    help="archive subdirectory name (pass a date from the caller)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    proposals = Path(args.workdir) / ".build-loop" / "proposals"
    if not proposals.is_dir():
        print(f"no proposals directory at {proposals}", file=sys.stderr)
        return 2

    result = drain(proposals)

    if args.json:
        print(json.dumps({
            "total_files": result["total_files"],
            "unique_findings": result["unique_findings"],
            "superseded": len(result["superseded"]),
            "stale": len(result["stale"]),
            "non_actionable": len(result["non_actionable"]),
            "actionable": len(result["actionable"]),
            "buckets": {k: len(v) for k, v in result["buckets"].items()},
        }, indent=2))
    else:
        print(f"proposals: {result['total_files']} files -> {result['unique_findings']} unique findings")
        print(f"  superseded re-emissions : {len(result['superseded'])}")
        print(f"  stale (no longer true)  : {len(result['stale'])}")
        print(f"  non-actionable by class : {len(result['non_actionable'])}")
        print(f"  ACTIONABLE              : {len(result['actionable'])}")
        print()
        for name, items in sorted(result["buckets"].items(), key=lambda kv: -len(kv[1])):
            print(f"  {name:16} {len(items)}")

    if args.archive:
        moved = archive(result, proposals, args.stamp)
        print(f"\narchived {moved} files to {proposals / 'archive' / args.stamp}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
