#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""Add `chunk_context TEXT` column to semantic_facts + backfill existing rows.

Phase D — write-side Anthropic Contextual Retrieval. The column stores
the dense ~80-token "this decision comes from {context}" summary
generated by `contextual_prepend.generate_chunk_context`. The column is
included in the embedding text on write (in `write_decision.db_dualwrite`)
and in the GENERATED tsvector (after running
`migrate_extend_search_vector_with_context.py`).

Idempotent. Re-running:
  - DDL: `ADD COLUMN IF NOT EXISTS` (no-op when present)
  - Backfill: skips rows whose `chunk_context IS NOT NULL` (re-runnable
    safely; never overwrites existing summaries unless --force is set)

Usage:
    uv run --extra db python3 scripts/migrate_add_chunk_context_column.py
    uv run --extra db python3 scripts/migrate_add_chunk_context_column.py \
         --schemas build_loop_memory --dry-run
    uv run --extra db python3 scripts/migrate_add_chunk_context_column.py \
         --skip-backfill        # add column only; backfill later
    uv run --extra db python3 scripts/migrate_add_chunk_context_column.py \
         --force                # re-generate even when chunk_context already set

When the local LLM router is unavailable (no Ollama models pulled), the
backfill skips silently — the column stays NULL and the row continues
to embed via subject/predicate/object alone (the pre-Phase-D path).

Exit:
  0 success (or no-op)
  1 validation error
  2 DB / backend error
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

try:
    from db import execute, query, vector_literal  # type: ignore
except Exception as _db_import_err:  # noqa: BLE001
    execute = None  # type: ignore
    query = None  # type: ignore
    vector_literal = None  # type: ignore
    _DB_IMPORT_ERR: Exception | None = _db_import_err
else:
    _DB_IMPORT_ERR = None

SCHEMA_RE = re.compile(r"^[a-z][a-z0-9_]*$")
DEFAULT_SCHEMAS = ("build_loop_memory", "personal_memory")
DEFAULT_BATCH = 16


def _safe_schema(s: str) -> str:
    if not SCHEMA_RE.match(s):
        raise ValueError(f"unsafe schema name: {s!r}")
    return s


def _column_exists(schema: str, column: str) -> bool:
    rows = query(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_schema = %s AND table_name = 'semantic_facts' "
        "  AND column_name = %s",
        (schema, column),
    )
    return bool(rows)


def add_column(schema: str, *, dry_run: bool) -> dict:
    """ADD COLUMN IF NOT EXISTS chunk_context TEXT."""
    schema = _safe_schema(schema)
    status: dict = {"schema": schema}
    has = _column_exists(schema, "chunk_context")
    status["had_column"] = has
    if has:
        status["action"] = "noop"
        return status
    if dry_run:
        status["action"] = "would-add-column"
        return status
    execute(f"ALTER TABLE {schema}.semantic_facts ADD COLUMN chunk_context TEXT")  # nosec: schema is a validated identifier (^[a-z][a-z0-9_]*$); values bound as params
    status["action"] = "added-column"
    return status


def backfill(
    schema: str,
    *,
    dry_run: bool,
    force: bool,
    batch_size: int,
) -> dict:
    """Generate chunk_context for rows that don't have one and re-embed.

    Each backfilled row also gets re-embedded so the vector column
    reflects the new prepended text. Without re-embed, the column is
    populated but retrieval still rides on the old vector — the spec
    explicitly calls for re-embed during backfill.
    """
    schema = _safe_schema(schema)
    summary: dict = {"schema": schema, "candidates": 0, "filled": 0, "errors": 0}

    where_clause = "" if force else " WHERE chunk_context IS NULL"
    rows = query(
        f"SELECT id::text AS id, subject, predicate, object "
        f"FROM {schema}.semantic_facts {where_clause}"
    )
    summary["candidates"] = len(rows)
    if not rows:
        summary["action"] = "noop"
        return summary

    if dry_run:
        summary["action"] = f"would-backfill-{len(rows)}"
        return summary

    # Lazy imports — these may pull torch/sentence-transformers etc.
    try:
        from contextual_prepend import (  # type: ignore  # noqa: PLC0415
            available_router_target,
            generate_chunk_context,
        )
    except Exception as e:  # noqa: BLE001
        summary["action"] = f"router-import-failed: {e}"
        return summary

    target = available_router_target()
    if not target:
        summary["action"] = "no-router-target-skip"
        return summary
    summary["router_model"] = target

    try:
        from embed_backend import active_model, embed  # type: ignore  # noqa: PLC0415
    except Exception as e:  # noqa: BLE001
        summary["action"] = f"embed-import-failed: {e}"
        return summary

    model_id = active_model()

    # Process serially for now — most local models can't handle parallel
    # POSTs cleanly, and the corpus is small (~10–20 rows). Batch flag
    # is reserved for future use.
    _ = batch_size  # noqa: F841

    for row in rows:
        body = " ".join(filter(None, (row.get("subject"), row.get("predicate"), row.get("object"))))
        if not body.strip():
            continue
        try:
            ctx = generate_chunk_context(body, model=target)
        except Exception as e:  # noqa: BLE001
            print(f"backfill: generate failed for id={row['id']}: {e}", file=sys.stderr)
            summary["errors"] += 1
            continue
        if not ctx:
            # Router fell through; skip silently (no chunk_context).
            continue

        # Re-embed using the prepended text, mirroring the new write path.
        embed_text = f"{ctx}\n\n{body}"
        try:
            vec = embed(embed_text)
        except Exception as e:  # noqa: BLE001
            print(f"backfill: embed failed for id={row['id']}: {e}", file=sys.stderr)
            summary["errors"] += 1
            continue

        try:
            execute(
                f"UPDATE {schema}.semantic_facts "  # nosec: schema is a validated identifier (^[a-z][a-z0-9_]*$); values bound as params
                f"SET chunk_context = %s, embedding = %s::vector, "
                f"    embedding_model_version = %s "
                f"WHERE id::text = %s",
                (ctx, vector_literal(vec), model_id, row["id"]),
            )
            summary["filled"] += 1
        except Exception as e:  # noqa: BLE001
            print(f"backfill: update failed for id={row['id']}: {e}", file=sys.stderr)
            summary["errors"] += 1

    summary["action"] = f"backfilled-{summary['filled']}"
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schemas", default=",".join(DEFAULT_SCHEMAS))
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--skip-backfill", action="store_true",
                        help="Add the column and exit; backfill later.")
    parser.add_argument("--force", action="store_true",
                        help="Regenerate chunk_context even when already populated.")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH)
    args = parser.parse_args(argv)

    if _DB_IMPORT_ERR:
        print(f"db import failed: {_DB_IMPORT_ERR}", file=sys.stderr)
        return 2

    schemas = [s.strip() for s in args.schemas.split(",") if s.strip()]
    try:
        for s in schemas:
            _safe_schema(s)
    except ValueError as e:
        print(f"validation: {e}", file=sys.stderr)
        return 1

    overall_rc = 0
    for s in schemas:
        try:
            col_status = add_column(s, dry_run=args.dry_run)
            print(f"[ddl] {col_status}", file=sys.stderr)
        except Exception as e:  # noqa: BLE001
            print(f"[ddl] failed for {s}: {e}", file=sys.stderr)
            overall_rc = 2
            continue

        if args.skip_backfill:
            continue

        try:
            bf = backfill(
                s,
                dry_run=args.dry_run,
                force=args.force,
                batch_size=args.batch_size,
            )
            print(f"[backfill] {bf}", file=sys.stderr)
        except Exception as e:  # noqa: BLE001
            print(f"[backfill] failed for {s}: {e}", file=sys.stderr)
            overall_rc = 2

    return overall_rc


if __name__ == "__main__":
    sys.exit(main())
