#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025-2026 Tyrone Ross, Jr <46267523+tyroneross@users.noreply.github.com>
# SPDX-License-Identifier: Apache-2.0
"""File-side effects: INDEX.md regeneration, events.jsonl append, history archive.

The INDEX layout, the events.jsonl line format, and the `_history/` archive
naming are all on-disk contracts; this module keeps them byte-for-byte
identical to the historical flat module.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from constants import CONFIDENCE_ORDER, LockedFile, VALID_EVENT_KINDS, atomic_write_bytes
from frontmatter import _FM_RE, emit_frontmatter, parse_frontmatter
from ids import list_decisions


# ---------- INDEX regenerate ----------


def regenerate_index(decisions_dir: Path, confidence_floor: str = "confirmed") -> None:
    """Write `decisions/INDEX.md` with rollup of frontmatter.

    Filters by `confidence >= floor` per design §10 (default confirmed).
    """
    floor = CONFIDENCE_ORDER[confidence_floor]
    rows: list[tuple[str, dict, Path]] = []
    for f in list_decisions(decisions_dir):
        fm = parse_frontmatter(f.read_text(encoding="utf-8")) or {}
        conf = fm.get("confidence", "assumed")
        if CONFIDENCE_ORDER.get(conf, 0) < floor:
            continue
        rows.append((str(fm.get("canonical_id") or fm.get("id", "")), fm, f))
    rows.sort(key=lambda r: r[0])

    lines = [
        "# Decisions — INDEX",
        "",
        f"_Auto-generated by `scripts/regenerate_knowledge_index.py`. Default filter: confidence ≥ {confidence_floor}._",
        "",
        "| id | date | title | primary_tag | entity | confidence | status |",
        "|---|---|---|---|---|---|---|",
    ]
    for did, fm, f in rows:
        lines.append(
            f"| {did} | {fm.get('date','')} | [{fm.get('title','')}]({f.name}) | "
            f"{fm.get('primary_tag','')} | {fm.get('entity','')} | "
            f"{fm.get('confidence','')} | {fm.get('status','')} |"
        )
    if not rows:
        lines.append("| _(no entries at or above confidence floor)_ |  |  |  |  |  |  |")
    out = "\n".join(lines) + "\n"
    atomic_write_bytes(decisions_dir / "INDEX.md", out.encode("utf-8"))


# ---------- events.jsonl append ----------


def append_event(events_path: Path, event: dict) -> None:
    if event.get("kind") not in VALID_EVENT_KINDS:
        raise ValueError(f"event kind must be in vocabulary; got {event.get('kind')!r}")
    with LockedFile(events_path):
        existing = events_path.read_bytes() if events_path.exists() else b""
        line = (json.dumps(event, ensure_ascii=False) + "\n").encode("utf-8")
        atomic_write_bytes(events_path, existing + line)


def iso_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def archive_to_history(prior_path: Path, prior_fm: dict, history_dir: Path, new_id: str) -> Path:
    """Move prior_path to history_dir/<id>-vN.md, updating frontmatter.

    `_history/` filenames follow `<id>-v<N>.md` where N starts at 1 and
    increments based on existing versions for the same id.
    """
    pid = prior_fm.get("id", "0000")
    # Determine version
    versions = []
    for f in history_dir.glob(f"{pid}-v*.md"):
        m = re.match(rf"^{pid}-v(\d+)\.md$", f.name)
        if m:
            versions.append(int(m.group(1)))
    next_version = (max(versions) + 1) if versions else 1
    dest = history_dir / f"{pid}-v{next_version}.md"

    # Update frontmatter on the prior body.
    text = prior_path.read_text(encoding="utf-8")
    fm = parse_frontmatter(text) or {}
    fm["status"] = "superseded"
    fm["superseded_by"] = new_id
    # Strip frontmatter from text and reattach updated version.
    body = _FM_RE.sub("", text, count=1)
    new_text = emit_frontmatter(fm) + body
    atomic_write_bytes(dest, new_text.encode("utf-8"))
    # Remove the prior from decisions/ root.
    try:
        prior_path.unlink()
    except FileNotFoundError:
        pass
    return dest
